version: '3'
services:
  hms:
    image: galsl/hms:dev
    container_name: hms
    environment:
      # S3_ENDPOINT the CEPH/RGW end-point-url 
      - S3_ENDPOINT=192.168.122.1:8000
      - S3_ACCESS_KEY=b2345678901234567890
      - S3_SECRET_KEY=b234567890123456789012345678901234567890
    # the container starts with booting the hive metastore
    command: sh -c '. ~/.bashrc; start_hive_metastore'
    ports:
      - 9083:9083
    networks:
      - trino_hms

  trino:
    image: trinodb/trino:405
    container_name: trino
    volumes:
      # the trino directory contains the necessary configuration
      - ./trino:/etc/trino:Z
    ports:
      - 8080:8080
    networks:
      - trino_hms

networks:
  trino_hms:

